# Generated by Django 4.1.3 on 2022-11-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_itemtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(blank=True, to="web.tag"),
        ),
    ]
