# Generated by Django 4.1.3 on 2022-11-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_item_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="attrs",
            field=models.TextField(default="{}"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.TextField(unique=True),
        ),
    ]
